-- Keep the legacy unique-view table intact for older app bundles, while every
-- qualified playback from the current app appends an immutable event here.
create table if not exists public.health_post_view_events (
  id bigint generated by default as identity primary key,
  post_id uuid not null references public.health_posts(id) on delete cascade,
  owner_user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create index if not exists health_post_view_events_post_id_idx
  on public.health_post_view_events (post_id);

create index if not exists health_post_view_events_owner_user_id_idx
  on public.health_post_view_events (owner_user_id);

alter table public.health_post_view_events enable row level security;
revoke all on table public.health_post_view_events from anon, authenticated;
revoke all on sequence public.health_post_view_events_id_seq from anon, authenticated;
grant insert on table public.health_post_view_events to authenticated;
grant usage on sequence public.health_post_view_events_id_seq to authenticated;

create policy "Patients can append published health post views"
on public.health_post_view_events
for insert
to authenticated
with check (
  (select auth.uid()) = owner_user_id
  and exists (
    select 1
    from public.health_posts post
    where post.id = health_post_view_events.post_id
      and post.status = 'published'
  )
);

create or replace function private.adjust_health_post_view_event_count()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  update public.health_posts
  set views_count = views_count + 1
  where id = new.post_id;
  return new;
end;
$$;

revoke all on function private.adjust_health_post_view_event_count() from public, anon, authenticated;

drop trigger if exists health_post_view_events_adjust_count on public.health_post_view_events;
create trigger health_post_view_events_adjust_count
after insert on public.health_post_view_events
for each row execute function private.adjust_health_post_view_event_count();

create or replace function public.record_health_post_view(p_post_id uuid)
returns bigint
language plpgsql
security invoker
set search_path = ''
as $$
declare
  viewer_id uuid := auth.uid();
  updated_count bigint;
begin
  if viewer_id is null then
    raise exception 'Authentication is required.' using errcode = '42501';
  end if;

  select post.views_count
  into updated_count
  from public.health_posts post
  where post.id = p_post_id
    and post.status = 'published';

  if not found then
    raise exception 'Published health post not found.' using errcode = 'P0002';
  end if;

  insert into public.health_post_view_events (owner_user_id, post_id)
  values (viewer_id, p_post_id);

  return updated_count + 1;
end;
$$;

revoke all on function public.record_health_post_view(uuid) from public, anon;
grant execute on function public.record_health_post_view(uuid) to authenticated;
